version: '3'

services:
  dev_env:
    build: ./
    restart: always
    volumes:
      - ./:/www/modules/communication
    ports:
      - "4800:4800"
      - '49153:49153'
    environment:
      ADMISSION: 'true'
volumes:
    modules: